### ISSUE TITLE
Clarity / UX tweaks

### ISSUE THREAD

**Issue by rmars** [runconduit/conduit-examples#28]
Make the following changes to make things clearer to people using the `emojivoto` demo application:
- [x] #29 the Poop page should have an explanation about why it’s broken
- [x] #29 add an optional step to README.md describing how to provide auto-generated load (i.e. deploying the vote-bot)
- [x] #36 Remove svc from names of emoji.voto deployments
- [x] #36 for consistency with the other configurations, vote-bot should address the web service as "web-svc.emojivoto:80", instead of "web-svc:80" as it does currently

**Comment by rmars** [comment]
Done
